#:schema node_modules/wrangler/config-schema.json
name = "harumaxy-com"
compatibility_date = "2024-06-03"
pages_build_output_dir = ".svelte-kit/cloudflare"


[[d1_databases]]
binding = "DB"                                       # i.e. available in your Worker on env.DB
database_name = "harumaxy-com-db"
database_id = "12cc0df2-7001-4057-a391-62243308883b"
migrations_dir = "./src/lib/db/drizzle"
preview_database_id = "DB"
